### ISSUE TITLE
Remote read not working as expected

### ISSUE THREAD

**Issue by saket9550** [timescale/timescale-prometheus#114]
Hi Team,
I am able to successfully write metrics to connector in the same format as remote write api of prometheus.I can see metrics in timescaledb.
But when I try to read the metrics using PromQL from prometheus dashboard, I don't see custom metrics that I manually wrote.
I can see other metrics in prometheus like node exporter metrics,etc.
Can you please help me resolve this issue?

**Comment by antekresic** [comment]
Hey @saket9550 I believe we resolved this issue, it was a problem with Prometheus configuration. 

For future reference, in order for Prometheus to read backfilled data from remote read endpoint, you should set:
```
read_recent: true
```
Reference: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read

Can we close this issue?

**Comment by saket9550** [comment]
yes Thanks a lot Ante.
