### ISSUE TITLE
Unable to find sample-docker-prometheus.yml file in GitHub repository.

### ISSUE THREAD

**Issue by asharabu** [timescale/timescale-prometheus#130]
Hi,

I tried to deploy timescale-prometheus using the docker-compose file provided in GitHub [repository ](https://github.com/timescale/timescale-prometheus). But I can't see the sample-docker-prometheus.yml file which needed to deploy using docker-compose.yml.

**Comment by antekresic** [comment]
sample-docker-prometheus.yml is a placeholder path which you should substitute with the real path of your Prometheus configuration file.

Might be worth to update that path to something that indicates its a placeholder more clearly.

**Comment by ashar-abu** [comment]
Thanks.

**Comment by asharabu** [comment]
Thanks.
