### ISSUE TITLE
ERROR: could not open extension control file "/usr/share/postgresql/12/extension/timescale_prometheus_extra.control": No such file or directory

### ISSUE THREAD

**Issue by asharabu** [timescale/timescale-prometheus#133]
Hi,

I am looking for to use timescale-promethues with my existing postgres container. I have installed timescaleDB on my postgres container using the [link](https://docs.timescale.com/latest/getting-started/installation/debian/installation-apt-debian) and enabled timescaledb extension after that I am getting below error in timescale-prometheus container. Please let me know what I need to do to activate this extension,

> 

db_1                              | 2020-06-23 14:49:00.717 UTC [56] ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/timescale_prometheus_extra.control": No such file or directory
db_1                              | 2020-06-23 14:49:00.717 UTC [56] STATEMENT:  CREATE EXTENSION IF NOT EXISTS timescale_prometheus_extra WITH SCHEMA _prom_ext;

> 

I have tried  CREATE EXTENSION IF NOT EXISTS timescale_prometheus_extra WITH SCHEMA _prom_ext; this command on postgres database but there I am getting below error,

> postgres=# CREATE EXTENSION IF NOT EXISTS timescale_prometheus_extra WITH SCHEMA _prom_ext;
ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/timescale_prometheus_extra.control": No such file or directory

>

**Comment by cevian** [comment]
You need to also install the extension here: https://github.com/timescale/timescale-prometheus/tree/master/extension. But this should be optional. The connector should work without the extension as well. This extension just adds some performance improvements
