### ISSUE TITLE
Use too much connections

### ISSUE THREAD

**Issue by wenerme** [timescale/timescale-prometheus#187]
* timescaledb
  * docker install - latest
  * 16G max-connection 500
* tow timescale/timescale-prometheus - docker installed latest
  * used all connections, still reporting `FATAL: sorry, too many clients already (SQLSTATE 53300)`
* promethes - 10 node-exporter

timescale-prometheus use prepared statement, so can not use transaction polling to reduce the connections.

**Comment by wenerme** [comment]
latest docker image not updated yet, current latest use about 100 connection per instance

**Comment by cevian** [comment]
@wenerme The docker image for beta.2 released today should contain a fix for this. Can you please verify?
