### ISSUE TITLE
Long running unstable

### ISSUE THREAD

**Issue by wenerme** [timescale/timescale-prometheus#193]
Love timescale-prometheus, hope it better.

## use too much disk space

* After running 10 days, use 20G+ disk
  * docker installed
  * 6 node_exporter

I don't expected timescale-prometheus use too much disk storage, so I don't mount the data do data disk, this cause the rootfs out of space, delete the docker restored the space.

![image](https://user-images.githubusercontent.com/1777211/90220496-e2a2a200-de3a-11ea-86b5-e57805e2a100.png)

## use all cpus

Another instance, running 7 days on a 40 core server, restart the docker everything goes normal.

Load

![image](https://user-images.githubusercontent.com/1777211/90220670-3a410d80-de3b-11ea-8ca8-0921d1f91efa.png)

CPU
![image](https://user-images.githubusercontent.com/1777211/90222460-aa9d5e00-de3e-11ea-941d-8f280c981a49.png)

A lot context switch

![image](https://user-images.githubusercontent.com/1777211/90224596-7af05500-de42-11ea-9c12-022d4f5ec35b.png)

**Comment by JLockerman** [comment]
That's odd, I wouldn't expect it use much disk, unless the logs were very frequent.
@wenerme can you share what workload was the connector running, and possibly a sample of the logs?

**Comment by wenerme** [comment]
only observed once of the disk case, I will record the log when I got this again.

but got several cpu case.

**Comment by cevian** [comment]
Note: #204 may fix this.

**Comment by wenerme** [comment]
upgrade to beta.3, if there any problem related to beta.3 will open another issues, this is outdated.
