### ISSUE TITLE
[beta.2] use more connection and more cpu

### ISSUE THREAD

**Issue by wenerme** [timescale/timescale-prometheus#202]
```sql
select datname,count(*) FROM pg_stat_activity group by datname;
```

| datname | count |
| :--- | :--- |
| instanceA | 200 |
| timescale | 2 |
| instanceB | 801 |
| postgres | 1 |
| NULL | 6 |

instanceB's cpu is normal

instanceA's cpu is very high, and report logs

```
{"caller":"write.go:70","err":"The insert routine has previously failed with failed to connect to `host=10.0.1.1 user=username database=instanceA`: server error (FATAL: sorry, too many clients already (SQLSTATE 53300))","level":"warn","msg":"Error sending samples to remote storage","num_samples":100,"ts":"2020-08-20T08:21:03.129Z"}
```

and a lot duplicate log

```
{"caller":"sql_ingest.go:524","duplicate_count":6,"level":"warn","msg":"duplicate data in sample","row_count":6,"table":"ifInDiscards","ts":"2020-08-20T08:22:07.953Z"}
```

**Comment by wenerme** [comment]
after increase db connections, db restarted, the error still exists,  timescale-prometheus can not recover from the error

still reporting `server error (FATAL: sorry, too many clients already (SQLSTATE 53300))`

when

| datname | count |
| :--- | :--- |
| instanceA | 167 |
| timescale | 2 |
| instanceB | 196 |
| postgres | 1 |
| NULL | 6 |

```sql
show max_connections;
# 1800
```

have to restart the instance, then everything goes normal, but the connection still high

| datname | count |
| :--- | :--- |
| instanceA | 392 |
| timescale | 2 |
| instanceB | 498 |
| postgres | 1 |
| NULL | 6 |

**Comment by wenerme** [comment]
Dose timescale-prometheus still use prepare statement ? I don't find any code related to prepare, if timescale-prometheus do not use prepare, so I can setup a pool for tsdb.

timescale-prometheus use a lot connections, and this is risky, not scaleable, increase the max_connection is a temporary fix, when add more tenant/instance,  about 500 connection per tenant is unacceptable.

**Comment by wenerme** [comment]
after long running ,connection reduced to about 100,

| datname | count |
| :--- | :--- |
| instanceA | 101 |
| instanceB | 161 |

instanceA samples about 1200/s
instanceB samples about 900/s

![image](https://user-images.githubusercontent.com/1777211/90779604-9969bb00-e330-11ea-8ed9-1385f76d004c.png)

**Comment by cevian** [comment]
Hmm. Part of this should be improved by https://github.com/timescale/timescale-prometheus/pull/204. But there is still some a bit of weirdness here with the number of connections. What did you mean by `have to restart the instance, then everything goes normal, but the connection still high` which instance did you restart db, connector, something else?

**Comment by cevian** [comment]
@JLockerman one thing here is that out automatic figure-out max_connections logic does not take into account how many connections are already used. That's one issue.

**Comment by wenerme** [comment]
> have to restart the instance, then everything goes normal, but the connection still high

After increase the max connections to 1800, then restart the db, instanceA timescale-prometheus still reporting `too many clients already`, seems the connection is not reconnect.

Then I restart the instance, the error is gone.

---

Upgrade timescale-prometheus makes the prometheus accumulate a lot metrics, maybe that's why after upgrade, the connection goes very high.

**Comment by cevian** [comment]
@wenerme we addressed the number of connections used by default in issue in #209. You can also control the max number of connections explicitly used using the cli flag `db-connections-max` a value of 50 is recommended for your case. #209 will be in our next release.

**Comment by wenerme** [comment]
upgrade to beta.3, set the db-connections-max to 50.close this issues now.
