### ISSUE TITLE
read use a lot more memory

### ISSUE THREAD

**Issue by wenerme** [timescale/timescale-prometheus#208]
![image](https://user-images.githubusercontent.com/1777211/90914435-7d3d4b00-e410-11ea-9c36-0bfe0cd63dd7.png)

row 2 is instanceB in this issues https://github.com/timescale/timescale-prometheus/issues/202
row 3 is instanceA, about samples 1.2k/s, log is normal.

both instance use same connections, 161

---

any recommended memory for timescale-prometheus, I don't expected  timescale-prometheus use too much memory.

---

instanceA has some read request, but used more than 600M memory, cache metrics shows this

```
ts_prom_label_cache_capacity 10000
ts_prom_label_cache_elements_stored 2148
ts_prom_metric_name_cache_capacity 10000
ts_prom_metric_name_cache_elements_stored 648
```

![image](https://user-images.githubusercontent.com/1777211/90915205-b75b1c80-e411-11ea-977e-9b40d70ca372.png)

**Comment by JLockerman** [comment]
Could you send us the heap allocation info for this instance? You can get it by running
```bash
curl http://$YOUR_ADDRESS/debug/pprof/heap > heap.pprof
```
and either sending it to us, or running `go tool pprof` on it

**Comment by cevian** [comment]
@wenerme would it be possible to test this on beta.3 and see if this problem persists?

**Comment by wenerme** [comment]
@cevian I'll upgrade to beta.3 tomorrow.

This is current memory usage, setup a cron to restart tsdb-prom daily, because the cpu problem, maybe some problem will not appear.

![image](https://user-images.githubusercontent.com/1777211/91640303-227aa380-ea4f-11ea-8dc9-61c2dc71acee.png)

current load 

![image](https://user-images.githubusercontent.com/1777211/91640360-9ae16480-ea4f-11ea-8233-1d7c30e9326e.png)

**Comment by wenerme** [comment]
Even enabled daily restart, this still happen.

![image](https://user-images.githubusercontent.com/1777211/91652294-74abdb00-eac8-11ea-99b3-5fb8e75215ca.png)
![image](https://user-images.githubusercontent.com/1777211/91652301-8d1bf580-eac8-11ea-8756-9f09425918b7.png)

upgrade now.

**Comment by cevian** [comment]
@wenerme sorry I am not sure is the above on beta.3 or beta.2?

**Comment by wenerme** [comment]
running beta.3 for two days. with daily restart, set max connection to 50

![image](https://user-images.githubusercontent.com/1777211/91800656-f718d400-ec5b-11ea-8ce4-155d70f6ac70.png)
![image](https://user-images.githubusercontent.com/1777211/91800697-0b5cd100-ec5c-11ea-924a-146c33a7f142.png)

beta.3 use less memory.
should I close this now ?
