### ISSUE TITLE
Server refused TLS connection

### ISSUE THREAD

**Issue by clementDele** [timescale/timescale-prometheus#224]
Hello,

I'm having trouble to get timescale-prometheus running on my Debian. I'm using the `docker-compose.yml` located at the root of this project. I changed absolutely nothing but `timescale-prometheus-connector` won't work: it tells me that there is a TLS error : 

```
timescale-prometheus-connector_1  | {"caller":"main.go:162","level":"info","msg":"Version:0.1.0-beta.3; Commit Hash: ","ts":"2020-08-28T11:55:49.380Z"}
timescale-prometheus-connector_1  | {"caller":"main.go:163","config":"&{listenAddr::9201 telemetryPath:/metrics-text pgmodelCfg:{host:db port:5432 user:postgres password:**** database:postgres sslMode:require dbConnectRetries:10 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:true corsOrigin:0xc000326500}","level":"info","ts":"2020-08-28T11:55:49.380Z"}
timescale-prometheus-connector_1  | {"caller":"main.go:174","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-08-28T11:55:49.380Z"}
timescale-prometheus-connector_1  | {"caller":"main.go:186","level":"error","msg":"Aborting startup because of migration error: Error while trying to open DB connection: failed to connect to `host=db user=postgres database=postgres`: tls error (server refused TLS connection)","ts":"2020-08-28T11:55:49.384Z"}
timescale-prometheus_timescale-prometheus-connector_1 exited with code 1
```

**Then** I tried to change the database image from `timescale/timescaledb:latest-pg12` to `timescaledev/timescale_prometheus_extra:latest-pg12` but the same error occurs.

**Then** I tried desabling migrate:

```
timescale-prometheus-connector_1  | {"caller":"main.go:162","level":"info","msg":"Version:0.1.0-beta.3; Commit Hash: ","ts":"2020-08-28T12:07:39.254Z"}
timescale-prometheus-connector_1  | {"caller":"main.go:163","config":"&{listenAddr::9201 telemetryPath:/metrics-text pgmodelCfg:{host:db port:5432 user:postgres password:**** database:postgres sslMode:require dbConnectRetries:10 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:false corsOrigin:0xc0000ba0a0}","level":"info","ts":"2020-08-28T12:07:39.255Z"}
timescale-prometheus-connector_1  | {"caller":"main.go:174","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-08-28T12:07:39.255Z"}
timescale-prometheus-connector_1  | {"caller":"client.go:76","err configuring number of connections":"failed to connect to `host=db user=postgres database=postgres`: tls error (server refused TLS connection)","level":"error","ts":"2020-08-28T12:07:39.262Z"}
timescale-prometheus-connector_1  | {"caller":"main.go:195","failed to connect to `host=db user=postgres database=postgres`: tls error (server refused TLS connection)":"(MISSING)","level":"error","ts":"2020-08-28T12:07:39.262Z"}
```

But nothing succesfull.

**Then** I saw that there is `sslMode` in the `pgclient` config : https://github.com/timescale/timescale-prometheus/blob/e62d9f1432812397522e8588ea2e56a2edc59f85/pkg/pgclient/client.go#L31 

However, it does not seems configurable by command-line arguments.

I'm stuck and at this point, i need help on this one please :)

Thank you and keep up the good work 👍

**Comment by antekresic** [comment]
Hey there!

Did you try the `db-ssl-mode` flag? It should be configurable:

https://github.com/timescale/timescale-prometheus/blob/e62d9f1432812397522e8588ea2e56a2edc59f85/pkg/pgclient/client.go#L49

Also, we just pushed the latest beta.3 version which should require SSL connection with the database as default. Can you try updating the version?

Thanks.

**Comment by clementDele** [comment]
Okay it doest work with `db-ssl-mode` to `disable` ! I put aside security for the moment as it is my first tries with `timescale-prometheus` ;) 

I use the `0.1.0-beta.3` since the beginning as you can see on the first line of the logs i sent and i can confirm that it requires SSL connection with the database by default, hence my problem haha.

You should make a note about this SSL connection enabled by default because new users (like me) who use your `docker-compose.yml` might ask you again.

I think the issue can be closed 

Thanks for the blazing fast response :)

**Comment by cevian** [comment]
Thanks @clementDele for reporting this. We filed and issue #225 to follow up on docker-compose.
