### ISSUE TITLE
Can not start timescale-prometheus with error

### ISSUE THREAD

**Issue by tr2vil** [timescale/timescale-prometheus#233]
Hi there,

I am new to timescale db and I am trying to use it as a prometheus long term storage.
At first, My OS is  Centos 7.
I downloaded timescale-prometheus binary, after then execute binary like this.

$ wget https://github.com/timescale/timescale-prometheus/releases/download/0.1.0-beta.3/timescale-prometheus_0.1.0-beta.3_Linux_x86_64
$ chmod 700 timescale-prometheus_0.1.0-beta.3_Linux_x86_64
$ ln -sf timescale-prometheus_0.1.0-beta.3_Linux_x86_64  timescale-prometheus
$ ./timescale-prometheus -db-ssl-mode=disable -log-level=debug

It generates erros.

{"caller":"main.go:162","level":"info","msg":"Version:0.1.0-beta.3; Commit Hash: ","ts":"2020-09-03T08:48:38.005Z"}
{"caller":"main.go:163","config":"&{listenAddr::9201 telemetryPath:/metrics pgmodelCfg:{host:localhost port:5432 user:postgres password: **** sslMode:disable dbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:true corsOrigin:0xc00015ea00}","level":"info","ts":"2020-09-03T08:48:38.005Z"}
{"caller":"main.go:174","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-09-03T08:48:38.005Z"}
{"caller":"main.go:186","level":"error","msg":"Aborting startup because of migration error: Error while trying to migrate DB: Error encountered during migration: error executing migration script: name idempotent/base.sql, err ERROR: function show_chunks(hypertable => text, older_than => timestamp with time zone) does not exist (SQLSTATE 42883)","ts":"2020-09-03T08:48:38.325Z"}

I don't know what there logs mean. 
I'm newbee at timescale-prometheus. what's wrong with me? plz let me know. thank you for reading this.

**Comment by Harkishen-Singh** [comment]
Thank you for reporting this. The logs seem to speak errors related to running migrations with the DB. I am not sure if this is just in the releases or if it was fixed in some PR after the release. Anyways, we will get back to this soon. Thank you.

**Comment by Harkishen-Singh** [comment]
@tr2vil can you mention the version of your timescale-db?

**Comment by tr2vil** [comment]
> @tr2vil can you mention the version of your timescale-db?

How can I check timescale-db's version ?

**Comment by tr2vil** [comment]
In additional, I want to build timescale-prometheus from source. 
According to the post, (https://github.com/timescale/timescale-prometheus/blob/master/docs/binary.md#-building-from-source) ,
I type this but not working. 

# Fetch the source code of Timescale-Prometheus in any directory
$ git clone git@github.com:timescale/timescale-prometheus.git
Cloning into 'timescale-prometheus'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is this repository is still working?

**Comment by Harkishen-Singh** [comment]
> How can I check timescale-db's version ?

```
SELECT default_version, installed_version FROM pg_available_extensions ORDER BY installed_version DESC LIMIT 1;
```

> update_from_version = 1.7.3

Seems like your db version is correct.

> I type this but not working.

Maybe, your ssh keys are not working. Anyways, try the HTTP way.

`git clone https://github.com/timescale/timescale-prometheus.git`

**Comment by tr2vil** [comment]
@Harkishen-Singh 

timescale db version is described below. 

tutorial=# SELECT default_version, installed_version FROM pg_available_extensions ORDER BY installed_version DESC LIMIT 1;
 default_version | installed_version 
-----------------+-------------------
 2.0.0-dev       | 2.0.0-dev

**Comment by Harkishen-Singh** [comment]
Could you try that command again? I just updated it. I had copied from my system as it was specific to me.
@tr2vil

**Comment by tr2vil** [comment]
@Harkishen-Singh 
I use timescale-prometheus for store prometheus exporter's metric into postgresql. 
anyway, you talked to me 
"Could you try that command again" 
which command do you mean? 

I compilied timescale-prometheus binary. and then try like this

# ls -al
total 23440
drwxr-xr-x 2 root root     4096 Sep  4 18:10 .
drwxr-xr-x 3 root root     4096 Sep  4 18:05 ..
-rw-r--r-- 1 root root    16270 Sep  4 18:05 main.go
-rw-r--r-- 1 root root     6920 Sep  4 18:05 main_test.go
-rwxr-xr-x 1 root root 23966576 Sep  4 18:10 timescale-prometheus

# ./timescale-prometheus -db-ssl-mode=disable -log-level=debug
{"caller":"main.go:181","level":"info","msg":"Version:0.1.0-beta.3.dev.0; Commit Hash: ","ts":"2020-09-04T09:11:13.192Z"}
{"caller":"main.go:182","config":"&{listenAddr::9201 telemetryPath:/metrics pgmodelCfg:{host:localhost port:5432 user:postgres password: **** sslMode:disable dbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:true stopAfterMigrate:false corsOrigin:0xc0002380a0}","level":"info","ts":"2020-09-04T09:11:13.192Z"}
{"caller":"main.go:193","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-09-04T09:11:13.193Z"}
{"caller":"main.go:206","level":"error","msg":"Aborting startup because of migration error: Error while trying to migrate DB: Error encountered during migration: error executing migration script: name idempotent/base.sql, err ERROR: function show_chunks(hypertable => text, older_than => timestamp with time zone) does not exist (SQLSTATE 42883)","ts":"2020-09-04T09:11:13.579Z"}


I'm sorry, but is it right way to start this binary to put the metrics of prometheus in postgresql?

**Comment by Harkishen-Singh** [comment]
> which command you mean?

`SELECT * FROM pg_available_extensions;`

The main aim behind this is to know the default and intalled version of Timescaledb and the extension. This should give the necessary output.

**Comment by tr2vil** [comment]
@Harkishen-Singh 

$ psql -U postgres -h localhost -d timescale
psql (12.4)
Type "help" for help.

timescale=# SELECT * FROM pg_available_extensions;
    name     | default_version | installed_version |                              comment                              
-------------+-----------------+-------------------+-------------------------------------------------------------------
 plpgsql     | 1.0             | 1.0               | PL/pgSQL procedural language
 timescaledb | 2.0.0-dev       |                   | Enables scalable inserts and complex queries for time-series data

**Comment by tr2vil** [comment]
@Harkishen-Singh 
In the timescale-prometheus doc, ( https://github.com/timescale/timescale-prometheus/blob/master/docs/binary.md#building-from-source) , 

It is said, prometheus remote write/read configuration is necessary to store prometheus metric
--
remote_write:
  - url: "http://<connector-address>:9201/write"
remote_read:
  - url: "http://<connector-address>:9201/read"

Is the 9201 port run by timescale-prometheus?

**Comment by Harkishen-Singh** [comment]
Yes, promethues should have that config and assuming that you are running locally, the connector address will be `localhost`.

Yes, 9201 is the port for timescale-prometheus. Prometheus will run and send live samples to port 9201 (on which connector is running).

**Comment by Harkishen-Singh** [comment]
@tr2vil could you confirm if everything is working for you after switching to `1.7.3` version for Timescaledb?

**Comment by tr2vil** [comment]
@Harkishen-Singh 
Yes, I'll remind to you after reinstall timescale-prometheus version 1.7.3.

**Comment by tr2vil** [comment]
@Harkishen-Singh @JLockerman ,
I had reinstalled timescale version 1.7.3.
After then, I re-execute success like this. I'll do more test. Thank you for your helping~!

'''
$ ./timescale-prometheus -db-ssl-mode=disable -log-level=debug
{"caller":"main.go:181","level":"info","msg":"Version:0.1.0-beta.3.dev.0; Commit Hash: ","ts":"2020-09-07T01:26:27.472Z"}
{"caller":"main.go:182","config":"&{listenAddr::9201 telemetryPath:/metrics pgmodelCfg:{host:localhost port:5432 user:postgres password: **** sslMode:disable dbConnectRetries:0 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1} logLevel:debug haGroupLockID:0 restElection:false prometheusTimeout:-1 electionInterval:5000000000 migrate:true stopAfterMigrate:false corsOrigin:0xc000183b80}","level":"info","ts":"2020-09-07T01:26:27.472Z"}
{"caller":"main.go:193","level":"warn","msg":"No adapter leader election. Group lock id is not set. Possible duplicate write load if running adapter in high-availability mode","ts":"2020-09-07T01:26:27.472Z"}
{"caller":"extension.go:51","level":"warn","msg":"timescale_prometheus_extra is not available, proceeding without extension","ts":"2020-09-07T01:26:27.498Z"}
{"caller":"client.go:81","level":"info","msg":"host=localhost port=5432 user=postgres dbname=timescale password='' sslmode=disable connect_timeout=10","numCopiers":32,"pool_max_conns":50,"pool_min_conns":8,"ts":"2020-09-07T01:26:27.512Z"}
{"caller":"query_engine.go:13","level":"debug","msg":"Lookback delta is zero, setting to default value","ts":"2020-09-07T01:26:27.516Z","value":"5m0s"}
{"caller":"main.go:316","level":"info","msg":"Starting up...","ts":"2020-09-07T01:26:27.516Z"}
{"addr":":9201","caller":"main.go:317","level":"info","msg":"Listening","ts":"2020-09-07T01:26:27.516Z"}
'''
