### ISSUE TITLE
POLL: Help us choose a new name for this project

### ISSUE THREAD

**Issue by akulkarni** [timescale/timescale-prometheus#243]
Now that this project is getting a lot of usage, we are considering giving it a new name (partly to give it its own identity, partly because we're tired of typing "timescale-prometheus" all the time 😁).

Here is the vision for this project:

- Serves as the analytics database for Prometheus metrics

- Supports full PromQL and SQL natively, so compatible with all SQL-based tools (including ML libraries / tools)

- Allows you to join Prometheus metrics with other data in your system

- Built on top of TimescaleDB, so includes native compression, horizontal scaling, high-performance, reliability, etc

- Summary: There are many long-term storage options available, but this one is uniquely focused on advanced analytics, enabled by the relational data model, in addition to basic PromQL, etc

We would really like feedback from Timescale-Prometheus users as well as from the general Prometheus community. In particular, we want to make sure that we are doing right by the Prometheus community and aren't breaking any public or unspoken naming guidelines. 

There is a list of names below. Please give the one(s) you like with a 👍 emoji. Please also feel free to leave any comments on why you like or don't like certain names. (And if you feel so inclined - feel free to suggest any names you might have as well 😊.)

Thanks!

**Comment by akulkarni** [comment]
Prombase

**Comment by akulkarni** [comment]
Promscale

**Comment by akulkarni** [comment]
Hestia

**Comment by akulkarni** [comment]
Lantern

**Comment by akulkarni** [comment]
FireTiger

**Comment by Harkishen-Singh** [comment]
> Promscale

To be very frank, I was about to say this in all hands yesterday. Happy to see the option. 😊.

Another one I thought was, Timetheus. But, I guess promscale is better than this, may be. 🤔

**Comment by akulkarni** [comment]
Thanks everyone for the votes so far! Question: Which one is your favorite, and why?

**Comment by Harkishen-Singh** [comment]
I believe Promscale is the perfect name since Timescale-Prometheus enables Prometheus to run without any worries (from the database layer side, making it more of a stateless kind of service (excluding WAL since 2 hours of data in WAL is less to be considered when you have years of metrics data)). This allows Prometheus to scale to new heights where sky is the limit.

**Comment by cevian** [comment]
I like *FireTiger* because of the bold visual it evokes

**Comment by niquola** [comment]
https://en.m.wikipedia.org/wiki/Aion_(deity)

**Comment by JLockerman** [comment]
@cevian the thing about _FireTiger_ is that the name gives no indication of what the project does. The others at least sound like proper nouns, and Promscale is _kinda_ explanatory, if you already know what Prometheus and Timescale are.

**Comment by JLockerman** [comment]
Some pros`+`/cons`-` for the current suggestions:

- **Prombase**
  - `+` sounds prometheus related
  - `-` kinda sounds like the backend for prometheus
- **Promscale**
  - `+` If you've heard of Prometheus and Timescale, you can probably figure out what it is
  - `+` sounds like what it does
- **Hestia**
  - `+` obviously a proper noun
- **Lantern**
  - pretty neutral, something like "Timescale Lantern" or "Prometheus Lantern" might be better
- **FireTiger**
  - `+` great imagery
  - `-` sounds like a kind of thing, not like the name of a thing

**Comment by recollir** [comment]
Portunus - the Roman god that originally protected warehouses. It also starts with a “P”.

**Comment by SuperQ** [comment]
I like the "Timescale Lantern", the url being `github.com/timescale/lantern` seems nice.

**Comment by bwplotka** [comment]
`Timeus` ! (: 

While `Promscale` sounds cool, I am not sure how Timescale actually scales Prometheus - while it claimed to be "scalable" looks like the selling point is that it offers unique usability features with SQL queries + analytics. But it's only my humble opinion.

`PromSQL` sounds cool also :wink:

**Comment by nvtkaszpir** [comment]
Chonker.

Sorry I just couldn't resist:
- Timescale already has a cat in the logo (tiger)
- timescaledb it supports big amount of data, that is usually sliced in chonks, erm chunks
- everyone loves cats
- this is a type of the cat you just let it rest in cozy place and keep feeding it with what it likes

;D

**Comment by cevian** [comment]
Thanks for the votes everyone. We decided to go with Promscale as seen in issue #267
