### ISSUE TITLE
scrape diffrence between prometheus and postgresql using timescale-prometheus

### ISSUE THREAD

**Issue by tr2vil** [timescale/timescale-prometheus#245]
Hi there~ 
In the lab, I scrape one target-host using prometheus node_exporter. and  I store metric into postgresql using timescale-prometheus. 

In prometheus, I can see the metric, but in postgresql there are not exist.
Doesn't timescale-prometheus save everything? Some metric tables store work well. but some are not.

Look like this.
[Prometheus]
![image](https://user-images.githubusercontent.com/5829306/92427964-d3f4a400-f1c8-11ea-8d60-3cba9553622c.png)

[Postgresql]
![image](https://user-images.githubusercontent.com/5829306/92428303-af4cfc00-f1c9-11ea-90b3-cd96cace9de6.png)

![image](https://user-images.githubusercontent.com/5829306/92428022-056d6f80-f1c9-11ea-9738-97d2abf6b7c4.png)

Is there any configuraion which metric store in timescale-prometheus?

**Comment by cevian** [comment]
Your data is there it's just that the query is querying the table node_memory_memtotal_bytes not node_memory_MemTotal_bytes (note difference in capitalization). This is a sql oddness: when specifying a view or table with capital letters you need to quote the table name. Eg. your query should be `select * from "node_memory_MemTotal_bytes"` (note the double quotes)

**Comment by tr2vil** [comment]
@cevian 
Thanks you. It works to me. ^^
