### ISSUE TITLE
Prometheus + TimescaleDB

### ISSUE THREAD

**Issue by redhatromero** [timescale/timescale-prometheus#253]
so i have a working prometheus setup, but I am trying to use timescale for storage.
at my postgres vm, i have run the timescaledb-tune and preloaded the timescaledb extension.
all that is fine afaik:
`[root@timescale-01 ~]# psql -U postgres -h localhost
psql (12.4)
Type "help" for help.

[main]
postgres=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
WARNING:
WELCOME TO
 _____ _                               _     ____________
|_   _(_)                             | |    |  _  \ ___ \
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 1.7.3
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/getting-started
 2. API reference documentation: https://docs.timescale.com/api
 3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.

CREATE EXTENSION
`

---
now im trying to connect prometheus to the database.
ive added the remote read/write lines:
`remote_write:
  - url: "http://172.7.2.145:9201/write"
remote_read:
  - url: "http://172.7.2.145:9201/read"
`
that ip is the postgresdb - and that is where i have compiled the connector but what i dont see is how to actually run it.

should i have compiled it on the prometheus servers instead?
and how does prometheus know to use it? how do i 'activate' the connector?

btw....
i am not doing this in docker. these are all standalone vms - right now im working in a vbox environment with individual vms. i see that there are three docker images being used to accomplish this, prometheus, timescaledb, and a third prometheus-timescaledb which is where the connector lives. 
do i have no choice but to use containers? i can but that would cause these last couple of weeks to be a waste.

thanks for any help you guys can provide.

**Comment by Harkishen-Singh** [comment]
You will have to run Timescale-prometheus either at container or locally. This will be responsible to receive the samples that Prometheus will send on `:9201`. Timescale-prometheus will insert these into its own schema in Timescaledb.

**Comment by redhatromero** [comment]
I failed to run the actual build - that might help :)
