### ISSUE TITLE
Can't find timescale/timescale-observability chart in timescale repository

### ISSUE THREAD

**Issue by jpigree** [timescale/timescale-prometheus#47]
Hi. I am new to timescaleDB. I am searching for a way to install it and send my Prometheus instances data on it. The [recommended way ](https://github.com/timescale/timescale-prometheus#quick-start-with-helm-recommended) is to use the timescale-observability chart.

However, it isn't available in the timescale chart repository.
```
helm search repo timescale
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
timescale/timescaledb-multinode 0.3.0                           TimescaleDB Multinode Deployment.
timescale/timescaledb-single    0.5.5                           TimescaleDB HA Deployment.
```

I will use the helm-git plugin to install it. However it would be awesome to either publish the chart since it is what the READMEs suggest ([here](https://github.com/timescale/timescale-observability#quick-start) and [here](https://github.com/timescale/timescale-prometheus#quick-start-with-helm-recommended)) or update them to tell us to use the git files instead.

**Comment by cevian** [comment]
These charts are in pre-production and so you need to include `--version=0.1.0-alpha.2` to the helm command because helm does not install or list alpha versions by default. The 0.1.0 chart should be out shortly

**Comment by jpigree** [comment]
Thanks. I didn't know that helm hide the alpha versions. It works with the version you mentioned.
