### ISSUE TITLE
Production setup installation

### ISSUE THREAD

**Issue by jpigree** [timescale/timescale-prometheus#48]
Hi. I am new to timescaleDB. I am searching for a way to install it and send my Prometheus instances data on it. The recommended way is to use the timescale-observability Helm chart.

Is this production ready? Or should I use instead the [Timescale AWS AMI](https://docs.timescale.com/latest/getting-started/installation/ami/installation-ubuntu-ami) for more stability?

Thanks for your help!

**Comment by cevian** [comment]
Hi @jpigree. TimescaleDB is production ready but this adapter is not. It's currently in alpha, and we don't support updates yet. We encourage you to test it out and we should be getting out of alpha within a short period of time, after which we will support updates.

**Comment by jpigree** [comment]
Okay. I will continue to experiment with it until the release.
Thanks for your reply.
