### ISSUE TITLE
Feature: Provide also direct PromQL interface

### ISSUE THREAD

**Issue by samsk** [timescale/timescale-prometheus#63]
It would be usefull if timescale-prometheus would also provide PromQL interface, to avoid additional data roundtrip via Prometheus when querying data via PromQL.
This should improve performance, reduce load on Prometheus and also maybe allow further SQL query optimizations. There is also problem, that when you are running multiple parallel prometheuses (HA setup), which one should handle do the remote_read request...
Using SQL interface (ie. from Grafana) makes reuse of existing dashboards much harder, and PromQL is easier to work with for sysadmins and other users, that are not SQL experts.

Having PromQL interface, makes it also easier to integrate Timescaledb with other PromQL compatible sources via [Promxy](https://github.com/jacksontj/promxy)- thats my use case - I'm aggregating multiple Prometheuses and Timescaledb.
Maybe see also related [Promxy Issue](https://github.com/jacksontj/promxy/issues/262#issuecomment-588319706)

Btw. thanks for this project, Few days ago I started to think about how to restructure my metrics storage to handle (read) load better, and you have come up with changes that seem to fix most of my problems ;-) And yes, having an SQL interfaces for analytical purposes, was my primary reason for choosing TimescaleDB and not VictoriaMetrics or similar...

**Comment by akulkarni** [comment]
Thanks for the thoughtful comment. We're discussing the best way to add a PromQL interface directly to timescale-prometheus. We'll aim to keep this issue updated.

> And yes, having an SQL interfaces for analytical purposes, was my primary reason for choosing TimescaleDB and not VictoriaMetrics or similar...

Glad to hear! Out of curiosity, what kinds of analytics are you looking to run? (eg what kinds of queries?)

**Comment by samsk** [comment]
Mostly outage reports now, what components fail, when, how often, critical components uptime (for status page) etc... Later mabye smth. more advanced.

**Comment by akulkarni** [comment]
We are aiming to add native PromQL support in the next release. Stay tuned!

**Comment by cevian** [comment]
This has been merged and will be out in the next release.

**Comment by samsk** [comment]
Thank you ;-)
