### ISSUE TITLE
histogram_quantile() function throws remote_read error

### ISSUE THREAD

**Issue by Atomicbeast101** [timescale/timescale-prometheus#91]
Prometheus: v2.17.1
Timescale-Prometheus: valpha.2
PostgreSQL: v11

Whenever I use histogram_quantile() function for any metrics, it keeps throwing the following error:
```
remote_read: error reading response: snappy: corrupt input
```

I am not sure if this is an issue on Prometheus' end or timescale-prometheus' end, but since its mentioning it's related to remote_read, I guess it's timescale-prometheus' end?

**Comment by antekresic** [comment]
I've been trying to reproduce this issue using the exact versions specified here but with no luck.

Any chance you can provide more info on how exactly you trigger this issue, @Atomicbeast101 ?

For reference, I tried something in line with:
`histogram_quantile(0.9, rate(prometheus_http_request_duration_seconds_bucket[10m]))`
but didn't get any issues.

**Comment by Atomicbeast101** [comment]
Running the same query above seems to work fine. Perhaps it's a mistake I made on my end somehow...

**Comment by cevian** [comment]
Could not reproduce
