### ISSUE TITLE
Where is prometheus_postgresql_extra extension at?

### ISSUE THREAD

**Issue by Atomicbeast101** [timescale/timescale-prometheus#92]
I am having a hard time trying to figure out where I can download prometheus_postgresql_extra to add to PostgreSQL as an extension. I am doing this though manual setup (ansible playbook) instead of using Helm.

**Comment by cevian** [comment]
It's in the `extension` directory of this repo. https://github.com/timescale/timescale-prometheus/tree/master/extension. The installation from source is just `make && make install`. Let us know if you run into any issues

**Comment by Atomicbeast101** [comment]
Running `make && make install` returns the following error:
```
src/support.c:9:10: fatal error: nodes/pathnodes.h: No such file or directory
    9 | #include <nodes/pathnodes.h>
      |          ^~~~~~~~~~~~~~~~~~~
```
According to quick google, it seems pathnodes.h is related to postgres. Should I have postgres dependency included?

**Comment by Atomicbeast101** [comment]
Could I get a follow-up on this? I would like to start testing the 0.1.0-alpha.3.1 version soon.

**Comment by tylerfontaine** [comment]
It requires postgres 12 to build. Usually this error indicates you're trying to build against an older version.

**Comment by Atomicbeast101** [comment]
@tylerfontaine Thank you! Turns out I needed postgresql-12-server-dev package through Debian in order to compile this.
