### ISSUE TITLE
Using the regex label matcher ==~ doesn't check right hand operand when using the extra extension

### ISSUE THREAD

**Issue by blagojts** [timescale/timescale-prometheus#96]
When using TimescaleDB with the Timescale-Prometheus Extra extension, if I write a query with a regex label matcher
```
SELECT *
FROM cpu_usage  u
WHERE labels ? ('namepace' ==~ 'dev')
```

It returns all the rows whose label value matches the 'dev'  regex, the right-hand side label-key ('namespace') is ignored

**Comment by cevian** [comment]
Fixed by #100
